### ISSUE TITLE
ModuleNotFoundError: No module named 'lottery_ticket'

### ISSUE THREAD

**Issue by eece-23** [google-research/lottery-ticket-hypothesis#5]
when I run "python mnist_fc/download_data.py", a error reported:

  File "mnist_fc/download_data.py", line 23, in <module>
    from lottery_ticket.foundations import save_restore
ModuleNotFoundError: No module named 'lottery_ticket'

I had run "python setup.py install" according https://github.com/google-research/lottery-ticket-hypothesis/pull/3

**Comment by joaolcaas** [comment]
Same error here. Did you found something?

**Comment by ActonMartin** [comment]
> Same error here. Did you found something?

Do some guys solve it?

**Comment by rahulvigneswaran** [comment]
@ActonMartin @joaolcaas @snowzjy 
Duplicate of #2 . Remove `lottery_ticket` from the `setup.py` file.

**Comment by nonobott** [comment]
Hello, I have the same issue. 

I have already remove lottery_ticket from setup.py , but still get: 

        Traceback (most recent call last):
        File "mnist_fc/download_data.py", line 23, in <module>
        from lottery_ticket.foundations import save_restore
        ModuleNotFoundError: No module named 'lottery_ticket'
on 

        python download_data.py

my catalogs structure are: 

       /home/johny/lottery-ticket/mnist_fc

Im run python as 

       python

At the same time, commands 

       python setup.py install 
       pip3 install . 

works successfully,

Is there any way to fix issue ? 

Thank you!

**Comment by NguyenVanThanhHust** [comment]
You can do this:
- Create folder: "lottery_ticket"
- Copy folder "foundations" and "mnist_fc" into folder "lottery_ticket"
- Move file "download_data.py" to out of "mnist_fc" folder
- modify file "download_data.py": change line 33: from def main(unused_argv): to def main():
- Run cmd: python download_data.py
